package GUI;

import javax.swing.JOptionPane;

/**
 * Έμα Παράθυρο διαλόγου για την επέκταση πληροφοριών ενός άρθρου από τον χρήστη.
 * Επιτρέπει την προσθήκη κατηγορίας, της βαθμολογίας και των σχολίων του χρήστη 
 * πριν την αποθήκευση.
 */
public class InformationExtensionDialog extends javax.swing.JDialog {
    private boolean isSave;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InformationExtensionDialog.class.getName());

    /**
     * Ο κατασκευαστής του παραθύρου για την επέκταση των πληροφοριών
     * 
     * @param parent Το κύριο frame (παράθυρο) της εφαρμογής
     * @param modal true για modal λειτουργία ("κλείδωμα" της εφαρμογής μέχρι να κλείσει το παράθυρο) 
     */
    public InformationExtensionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.isSave = false;
        initComponents();
    }
    
    /**
     * Ελέγχει αν πατήθηκε το κουμπί της αποθήκευσης στη βάση των δεδομένων.
     * 
     * @return true αν επιβεβαιώθηκε η αποθήκευση, αλλιώς false.
     */
    public boolean performedSave()    {
        return this.isSave;
    }
    
    /**
     * Ελέγχει αν δεδομένα εισόδου (κατηγορίς και σχολίων) είναι σύμφωνα 
     * με τους περιορισμούς της βάσης δεδομένων.
     * 
     * @return true αν τα δεδομένα είναι έγκυρα.
     */
    private boolean validateInputs() {
        // Έλεγχος για το μήκος χαρακτήρων της κατηγορίας
        if (txtFieldCategory.getText().length() > 255) 
        {
            showError("Category must be less than 255 characters long");
            return false;
        }

        // Έλεγχος για το μήκος χαρακτήρων των σχολίων 
        if (jTxtAreaComments.getText().length() > 2000) 
        {
            showError("Comments must be less than 2000 characters long");
            return false;
        }

        return true; 
    }
    
    private void showError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Validation Error", JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * Επιστρέφει την κατηγορία του άρθρου.
     * Μετατρέπει τη κατηγορία σε πεζά γράμματα και αφαιρεί τους "κενούς" χαρακτήρες
     * 
     * @return String Τη κατηγορία ή "χωρίς κατηγορία"
     */
    public String getCategory(){
        //έλεγχος του μήκους (varchar 255)
        String category = this.txtFieldCategory.getText().toLowerCase().strip();
        if (!category.isEmpty())
        {
            return category;
        }
        return "χωρίς κατηγορία";
        
    }
    /**
     * Λαμβάνει τη βαθμολογία του χρήστη (0-5).
     * 
     * @return Integer Τη βαθμολογία του χρήστη ή null
     */
    public Integer getRating() {
        javax.swing.JRadioButton[] buttons = {
            jRadioBtn0, jRadioBtn1, jRadioBtn2, jRadioBtn3, jRadioBtn4, jRadioBtn5
        };

        for (int i = 0; i < buttons.length; i++) {
            if (buttons[i].isSelected()) {
                return i;
            }
        }        
        return null;
    }
    
    /**
     * Επιστρέφει τα σχόλια του χρήστη ως String
     * 
     * @return String Τα σχόλια του χρήστη
     */
    public String getComments() {
        //έλεγχος του μήκους (varchar 2000)
        String comments = this.jTxtAreaComments.getText();
        return comments;
    }
    
    /**
     * Ορίζει την κατηγορία που προστεθεί στο άρθρο προς αποθήκευση
     * 
     * @param category Η κατηγορία
     */
    public void setCategory(String category) {
        if (category != null) {
            this.txtFieldCategory.setText(category);
        }
    }
    
    /**
     * Ορίζει το πεδίο των σχολίων για το άρθρο προς αποθήκευση
     * 
     * @param comments Το κείμενο των σχολίων
     */
    public void setComments(String comments) {
        if (comments != null) {
            this.jTxtAreaComments.setText(comments);
        }
    }
    
    /**
     * Ορίζει τη βαθμολογία του χρήστη για το άρθρο προς αποθήκευση
     * 
     * @param rating Ακέραιος αριθμός από 0 έως 5
     */
    public void setRating(Integer rating) {
        if (rating == null) {
            return;
        }
        // Επιλογή του σωστού RadioButton βάσει της βαθμολογίας
        switch (rating) {
            case 0: jRadioBtn0.setSelected(true); break;
            case 1: jRadioBtn1.setSelected(true); break;
            case 2: jRadioBtn2.setSelected(true); break;
            case 3: jRadioBtn3.setSelected(true); break;
            case 4: jRadioBtn4.setSelected(true); break;
            case 5: jRadioBtn5.setSelected(true); break;
            default: break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRatingGroup = new javax.swing.ButtonGroup();
        lblCategory = new javax.swing.JLabel();
        lblRating = new javax.swing.JLabel();
        lblComments = new javax.swing.JLabel();
        txtFieldCategory = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAreaComments = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jRadioBtn0 = new javax.swing.JRadioButton();
        jRadioBtn1 = new javax.swing.JRadioButton();
        jRadioBtn2 = new javax.swing.JRadioButton();
        jRadioBtn3 = new javax.swing.JRadioButton();
        jRadioBtn4 = new javax.swing.JRadioButton();
        jRadioBtn5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Additional Information Dialog");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setResizable(false);

        lblCategory.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCategory.setText("Category:");
        lblCategory.setPreferredSize(new java.awt.Dimension(52, 25));

        lblRating.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblRating.setText("Rating (1 - 5):");
        lblRating.setPreferredSize(new java.awt.Dimension(75, 25));

        lblComments.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblComments.setText("Comments:");
        lblComments.setPreferredSize(new java.awt.Dimension(60, 25));

        txtFieldCategory.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFieldCategory.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtFieldCategory.setPreferredSize(new java.awt.Dimension(70, 25));

        jTxtAreaComments.setColumns(20);
        jTxtAreaComments.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTxtAreaComments.setRows(5);
        jScrollPane1.setViewportView(jTxtAreaComments);

        btnSave.setText("Save");
        btnSave.setPreferredSize(new java.awt.Dimension(70, 25));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.setPreferredSize(new java.awt.Dimension(70, 25));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnRatingGroup.add(jRadioBtn0);
        jRadioBtn0.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioBtn0.setText("0");
        jRadioBtn0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioBtn0.setPreferredSize(new java.awt.Dimension(20, 40));
        jRadioBtn0.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnRatingGroup.add(jRadioBtn1);
        jRadioBtn1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioBtn1.setText("1");
        jRadioBtn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioBtn1.setPreferredSize(new java.awt.Dimension(20, 40));
        jRadioBtn1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnRatingGroup.add(jRadioBtn2);
        jRadioBtn2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioBtn2.setText("2");
        jRadioBtn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioBtn2.setPreferredSize(new java.awt.Dimension(20, 40));
        jRadioBtn2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnRatingGroup.add(jRadioBtn3);
        jRadioBtn3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioBtn3.setText("3");
        jRadioBtn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioBtn3.setPreferredSize(new java.awt.Dimension(20, 40));
        jRadioBtn3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnRatingGroup.add(jRadioBtn4);
        jRadioBtn4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioBtn4.setText("4");
        jRadioBtn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioBtn4.setPreferredSize(new java.awt.Dimension(20, 40));
        jRadioBtn4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnRatingGroup.add(jRadioBtn5);
        jRadioBtn5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioBtn5.setText("5");
        jRadioBtn5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioBtn5.setPreferredSize(new java.awt.Dimension(20, 40));
        jRadioBtn5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(txtFieldCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblRating, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jRadioBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblComments, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jRadioBtn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioBtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblComments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Χειρισμός event όπου πατιέται το κουμπί Save
     * @param evt 
     */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // ενημέρωση της μεταβλητής αποθήκευσης
        this.isSave = true;
        //έλεγχος των πεδίων
        if (!validateInputs()) 
        {
            return; // παύση ροής εκτέλεσης
        }
        //αποδέσμευση παραθύρου από το προσκήνιο
        this.setVisible(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * Χειρισμός event όταν πατιέται το κουμπί cancel
     * @param evt 
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.isSave = false;
        //αποδέσμευση παραθύρου από το προσκήνιο
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup btnRatingGroup;
    private javax.swing.JButton btnSave;
    private javax.swing.JRadioButton jRadioBtn0;
    private javax.swing.JRadioButton jRadioBtn1;
    private javax.swing.JRadioButton jRadioBtn2;
    private javax.swing.JRadioButton jRadioBtn3;
    private javax.swing.JRadioButton jRadioBtn4;
    private javax.swing.JRadioButton jRadioBtn5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtAreaComments;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblRating;
    private javax.swing.JTextField txtFieldCategory;
    // End of variables declaration//GEN-END:variables
}
