package GUI;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 * Η κλάση αποτελεί την αρχική οθόνη για την είσοδο στην εφαρμογή.
 * Ο χρήστης θα πρέπει να κάνει κλικ στην κεντρική εικόνα για να συνδεθεί 
 * στο κύριο περιβάλλον
 */
public class LoginScreen extends javax.swing.JPanel {

    /** Αναφορά στο κύριο παράθυρο για τη διαχείριση των εναλλαγών οθόνης */
    private final MainWindow mainWindow;
    
    /**
     * Ο κατασκευαστής της LoginscreenLoginScreen
     * Αρχικοποιεί τα elements για το γραγικό περιβάλλον και φορτώνει την εικόνα.
     * 
     * @param main Το αντικείμενο mainWindow.
     */
    public LoginScreen(MainWindow main) {
        this.mainWindow = main;
        initComponents();
        
        loadLoginImage();
        
        mainWindow.setStatusMessage("Press the Image to login");
    }
    
    /**
     * Φορτώνει την εικόνα για το Login σε ένα "κουμπί".
     * Σε περίπτωση που δεν θα μπορεί να εμφανιστεί η εικόνα, θα υπάρχει 
     * κατάλληλο μήνυμα κειμένου στο κουμπί.
     */
    private void loadLoginImage(){
        try {
            URL imgURL = getClass().getResource("/Images/Login.png");
            if (imgURL != null) {
                btnImage.setIcon(new ImageIcon(imgURL));
                btnImage.setText("");
            }
            else {
                btnImage.setText("The image was not found. Please click here to continue");
            }
        }
        catch (Exception e){
            btnImage.setText("Error loading the image.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        loginFrame = new javax.swing.JPanel();
        btnImage = new javax.swing.JButton();

        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        loginFrame.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        loginFrame.setLayout(new java.awt.GridBagLayout());

        btnImage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnImage.setToolTipText("\"Press the Image to Login\"");
        btnImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });
        loginFrame.add(btnImage, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(loginFrame, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        if (mainWindow != null) {
            mainWindow.showMain("Guest");
        }
    }//GEN-LAST:event_btnImageActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImage;
    private javax.swing.JPanel loginFrame;
    // End of variables declaration//GEN-END:variables
}
