package GUI;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import DBmanager.DBmanager;
import java.util.List;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.axis.NumberAxis;
import java.awt.GridLayout;

/**
 * Παράθυρο για την προβολή στατιστικών στοιχείων της εφαρμογής.
 * Χρησιμοποιεί τη βιβλιοθήκη JFreeChart για τη δημιουργία διαγραμμάτων (Bar Charts)
 * Τα διαγράμματα είναι για τις δημοφιλείς αναζητήσεις και 
 * για τις κατηγορίες των αποθηκευμένων άρθρων.
 */
public class StatisticsScreen extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StatisticsScreen.class.getName());
    private final DBmanager db;

    /**
     * Ο κατασκευαστής του παραθύρου για τα στατιστικά.
     * 
     * @param parent Το γονικό παράθυρο.
     * @param modal true για modal λειτουργία ("κλείδωμα" της εφαρμογής μέχρι να κλείσει το παράθυρο)
     * @param db Ο διαχειριστής της βάσης δεδομένων.
     */
    public StatisticsScreen(java.awt.Frame parent, boolean modal, DBmanager db) {
        super(parent, modal);
        this.db = db;
        
        initComponents();
        
        setTitle("Στατιστικά Δεδομένα");
        setSize(800, 800);
        
        initCharts();
    }
    
    /**
     * Αρχικοποιεί και δημιουργεί τα γραφήματα.
     */
    private void initCharts() {
        // Δημιουργία των Datasets
        DefaultCategoryDataset searchDataset = new DefaultCategoryDataset();        
        DefaultCategoryDataset categoryDataset = new DefaultCategoryDataset();
        
        // Ανάκτηση δεδομένων από τη βάση
        List<Object[]> searchStats = db.getSearchStatistics();
        List<Object[]> categoryStats = db.getCategoryStatistics();
        
        //Α :Δημιουργία διαγράμματος για τις αναζητήσεις (Search Statistics)
        if (searchStats != null){
            for (Object[] row : searchStats) {
            // row[0] = λέξη, row[1] = πλήθος
            searchDataset.addValue((Number) row[1], "Αναζητήσεις", (String) row[0]);
            }
        }
        
        // Δημιουργία του Bar Chart για τις αναζητήσεις
        JFreeChart searchChart = ChartFactory.createBarChart(
                "Δημοφιλείς Αναζητήσεις",   // Τίτλος
                "Λέξη Κλειδί",              // Άξονας Χ
                "Πλήθος",                   // Άξονας Υ
                searchDataset,              // Δεδομένα
                PlotOrientation.VERTICAL, 
                true,
                true,
                false);
        
        formatChartPlot(searchChart);
        
        //B :Δημιουργία διαγράμματος για τις κατηγορίες (category Statistics)
        if (categoryStats !=null){
             for (Object[] row : categoryStats) {
            // row[0] = λέξη, row[1] = πλήθος
            categoryDataset.addValue((Number) row[1], "Κατηγορίες", (String) row[0]);
            }
        }
        
        // Δημιουργία του Bar Chart για τις Κατηγορίες
        JFreeChart categoryChart = ChartFactory.createBarChart(
                "Δημοφιλείς Κατηγορίες",    // Τίτλος
                "Κατηγορία",                // Άξονας Χ
                "Πλήθος",                   // Άξονας Υ
                categoryDataset,            // Δεδομένα
                PlotOrientation.VERTICAL,       
                true,
                true,
                false);
        
        formatChartPlot(categoryChart);
        
        // Εμφάνιση των γραφημάων στο παράθυρο
        ChartPanel searchPanel = new ChartPanel(searchChart);
        add(searchPanel);
        ChartPanel categoryPanel = new ChartPanel(categoryChart);
        add(categoryPanel);
    }
    
    /**
     * Μορφοποιεί το Plot του γραφήματος ώστε οι άξονες να εμφανίζουν μόνο ακέραιες τιμές.
     * 
     * @param chart Το γράφημα προς μορφοποίηση.
     */
    private void formatChartPlot(JFreeChart chart) {
        CategoryPlot plot = chart.getCategoryPlot();
        NumberAxis yAxis = (NumberAxis) plot.getRangeAxis();
        // Εξασφάλιση ότι ο άξονας Υ δείχνει μόνο ακέραιους (π.χ. όχι 1.5 αναζήτηση)
        yAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
